language: node_js
sudo: 'false'
before_script:
- npm install -g polymer-cli
- git checkout package-lock.json
- >-
  npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
  Project is not formatted. Please run "npm run format".' && false)
node_js: node
addons:
  firefox: latest
  chrome: stable
script:
- xvfb-run polymer test --module-resolution=node --npm
dist: trusty
cache:
  directories:
  - node_modules
